Fixed tile scale computation (#6912)
MapServer/MapServer pull request #6925
Opened 2023-08-20 11:14 UTC by mikitex70

Fixed tile scale computation when the `UNITS` directive is used in the map (for example `UNITS dd`).
Added some test  to verify that the scale are computed correctly.

2023-08-20 21:47 UTC, geographika requested changes

2023-08-20 21:47 UTC, geographika commented on msautotest/misc/tiles_scales_z2.map
> +    MINSCALE 30000000
`MINSCALE` and `MAXSCALE` are deprecated. These should be replaced with `MINSCALEDENOM` and `MAXSCALEDENOM`.

2023-08-20 21:47 UTC, geographika commented on msautotest/misc/tiles_scales_z3.map
> +    MAXSCALE 70000000
As above

2023-08-20 21:47 UTC, geographika commented on msautotest/misc/tiles_scales_z4.map
> +    MAXSCALE 70000000
As above

2023-08-20 21:50 UTC, geographika commented
Thanks @mikitex70 for this, and for adding in the tests. 

For the tests could you add in 2 new images files (even if they are duplicates of `tile_scale_empty.png`) with names that match the test Mapfile? This is to ensure if a test fails it doesn't pick up a previously created file of the same name (see discussions in #6919).

2023-08-21 14:12 UTC, geographika approved these changes

2023-08-21 17:15 UTC, jmckenna commented
thanks @mikitex70 !

2023-08-21 17:16 UTC, merged